### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by abrown36** [Kurago-Software/node-red-contrib-azure#31]
I have this come up when I try to install:
Not quite sure what it means?

npm WARN config production Use `--omit=dev` instead.
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @kurago-dev/node-red-contrib-azure@1.0.7
npm ERR! notsup Not compatible with your version of node/npm: @kurago-dev/node-red-contrib-azure@1.0.7
npm ERR! notsup Required: {"node":">=16.0.0 <17.0.0","npm":">=8.0.0 <9.0.0"}
npm ERR! notsup Actual:   {"npm":"9.8.1","node":"v18.18.0"}

**Comment by kurago-dev** [comment]
Hello @abrown36,

This is an issue on our side, since the project is configured to only accept `node` versions `v16.x` (even though it should work with node `v18` and `v20`) and you are running `node`  `v18.18.0`. Also, it seems like in your `npm` configuration the `engine-strict` option is set to true. 

We'll try to fix it ASAP, but in the meantime a workaround could be:
1. Set the [`engine-strict`](https://docs.npmjs.com/cli/v7/using-npm/config#engine-strict) configuration flag to `false`. Depending on how you're using node-red, the steps might vary but some options are:
   - **NPM global settings:** set the value at the global npm configuration: `npm config set --location=global engine-strict false`
   - **NPM local settings:** locate your node-red folder and set the value locally: `npm config set engine-strict false`
2. Install the node. This step might be done via Node-RED's palette or via the `npm i` command.
3. Undo the configuration changes performed in step 1, resetting the `engine-strict` flag to `true`

Thanks for your issue and let us know if the workaround helps :)
